<?php
/** @var Develodesign\CategoryFaqExtension\ViewModel\Faq $faqVm */
/** @var HeroiconsSolid $heroiconsSolid */

use Hyva\Theme\ViewModel\HeroiconsSolid;

$faqVm = $block->getData('faq_vm');
$faqs = $faqVm->getFaqCollection();
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
?>

<?php if (count($faqs)) : ?>
    <div class="w-full mb-10" itemscope itemtype="https://schema.org/FAQPage">
        <h2 class="max-w-xl mx-auto pb-4 pt-10 pt-6 text-center text-xl"><?= __('Frequently Asked Questions') ?></h2>
        <div class="bg-white max-w-xl mx-auto border border-gray-200" x-data="{selected:<?= count($faqs) ?>}">
            <ul class="shadow-box">
                <?php foreach ($faqs as $key => $question) : ?>
                    <li class="relative border-b border-gray-200" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
                        <button type="button" class="w-full px-8 py-6 text-left text-lg" @click="selected !== <?= $key ?> ? selected = <?= $key ?> : selected = null">
                            <div class="flex items-center justify-between">
                                <span itemprop="name"><?= $question->getTitle() ?></span>
                                <?= $heroiconsSolid->chevronDownHtml() ?>
                            </div>
                        </button>
                        <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container<?= $key ?>" x-bind:style="selected == <?= $key ?> ? 'max-height: ' + $refs.container<?= $key ?>.scrollHeight + 'px' : ''">
                            <div class="px-10" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                                <span class="border-t w-full py-4 block text-gray-700 " itemprop="text"><?= $question->getAnswer() ?></span>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
    <style>
        .max-h-0 {
            max-height: 0;
        }
    </style>
<?php endif; ?>
